# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(712, 528)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_5 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_5.setMidLineWidth(1)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setHandleWidth(2)
        self.splitter_5.setObjectName("splitter_5")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(32, 32))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.projectBox = QtWidgets.QComboBox(self.tab_3)
        self.projectBox.setObjectName("projectBox")
        self.gridLayout_3.addWidget(self.projectBox, 0, 0, 1, 2)
        self.sampleView = QtWidgets.QListView(self.tab_3)
        self.sampleView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.sampleView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.sampleView.setProperty("showDropIndicator", False)
        self.sampleView.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.sampleView.setIconSize(QtCore.QSize(128, 128))
        self.sampleView.setResizeMode(QtWidgets.QListView.Adjust)
        self.sampleView.setViewMode(QtWidgets.QListView.IconMode)
        self.sampleView.setObjectName("sampleView")
        self.gridLayout_3.addWidget(self.sampleView, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 1)
        self.sampleViewSlider = QtWidgets.QSlider(self.tab_3)
        self.sampleViewSlider.setMinimum(32)
        self.sampleViewSlider.setMaximum(320)
        self.sampleViewSlider.setSingleStep(32)
        self.sampleViewSlider.setPageStep(64)
        self.sampleViewSlider.setProperty("value", 128)
        self.sampleViewSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sampleViewSlider.setObjectName("sampleViewSlider")
        self.gridLayout_3.addWidget(self.sampleViewSlider, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeSampleView = QtWidgets.QTreeView(self.tab_4)
        self.treeSampleView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeSampleView.setIconSize(QtCore.QSize(64, 64))
        self.treeSampleView.setObjectName("treeSampleView")
        self.gridLayout_2.addWidget(self.treeSampleView, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.treeSampleViewSlider = QtWidgets.QSlider(self.tab_4)
        self.treeSampleViewSlider.setMinimum(32)
        self.treeSampleViewSlider.setMaximum(320)
        self.treeSampleViewSlider.setSingleStep(32)
        self.treeSampleViewSlider.setPageStep(64)
        self.treeSampleViewSlider.setProperty("value", 64)
        self.treeSampleViewSlider.setOrientation(QtCore.Qt.Horizontal)
        self.treeSampleViewSlider.setObjectName("treeSampleViewSlider")
        self.gridLayout_2.addWidget(self.treeSampleViewSlider, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_4.sizePolicy().hasHeightForWidth())
        self.splitter_4.setSizePolicy(sizePolicy)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.splitter_3.sizePolicy().hasHeightForWidth())
        self.splitter_3.setSizePolicy(sizePolicy)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.Overview = QtWidgets.QTabWidget(self.splitter_3)
        self.Overview.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Overview.sizePolicy().hasHeightForWidth())
        self.Overview.setSizePolicy(sizePolicy)
        self.Overview.setTabPosition(QtWidgets.QTabWidget.South)
        self.Overview.setObjectName("Overview")
        self.metadataTab = QtWidgets.QWidget()
        self.metadataTab.setObjectName("metadataTab")
        self.Overview.addTab(self.metadataTab, "")
        self.overviewTab = QtWidgets.QWidget()
        self.overviewTab.setObjectName("overviewTab")
        self.Overview.addTab(self.overviewTab, "")
        self.imagePlace = QtWidgets.QWidget(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.imagePlace.sizePolicy().hasHeightForWidth())
        self.imagePlace.setSizePolicy(sizePolicy)
        self.imagePlace.setObjectName("imagePlace")
        self.spectra = QtWidgets.QTabWidget(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectra.sizePolicy().hasHeightForWidth())
        self.spectra.setSizePolicy(sizePolicy)
        self.spectra.setTabPosition(QtWidgets.QTabWidget.West)
        self.spectra.setObjectName("spectra")
        self.spectraTab = QtWidgets.QWidget()
        self.spectraTab.setObjectName("spectraTab")
        self.spectra.addTab(self.spectraTab, "")
        self.tablesTab = QtWidgets.QWidget()
        self.tablesTab.setEnabled(False)
        self.tablesTab.setObjectName("tablesTab")
        self.spectra.addTab(self.tablesTab, "")
        self.verticalLayout.addWidget(self.splitter_5)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayout.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 712, 30))
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setObjectName("menuFiles")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionClose_all_project = QtWidgets.QAction(MainWindow)
        self.actionClose_all_project.setObjectName("actionClose_all_project")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setMenuRole(QtWidgets.QAction.AboutQtRole)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.menuFiles.addAction(self.actionLoad)
        self.menuFiles.addAction(self.actionClose_all_project)
        self.menuFiles.addSeparator()
        self.menuFiles.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuFiles.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.Overview.setCurrentIndex(1)
        self.spectra.setCurrentIndex(0)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Icon size"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Icon view"))
        self.label_2.setText(_translate("MainWindow", "Icon size"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Tree view"))
        self.Overview.setTabText(self.Overview.indexOf(self.metadataTab), _translate("MainWindow", "Metadata"))
        self.Overview.setTabText(self.Overview.indexOf(self.overviewTab), _translate("MainWindow", "Overview"))
        self.spectra.setTabText(self.spectra.indexOf(self.spectraTab), _translate("MainWindow", "Spectra"))
        self.spectra.setTabText(self.spectra.indexOf(self.tablesTab), _translate("MainWindow", "Tables"))
        self.menuFiles.setTitle(_translate("MainWindow", "Files"))
        self.menuSettings.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionClose_all_project.setText(_translate("MainWindow", "Close all project"))
        self.actionQuit.setText(_translate("MainWindow", "quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

