# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WDSWidget.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WDSScanWidget(object):
    def setupUi(self, WDSScanWidget):
        WDSScanWidget.setObjectName("WDSScanWidget")
        WDSScanWidget.resize(634, 336)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(WDSScanWidget)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(WDSScanWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.selectionLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.selectionLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.selectionLayout.setContentsMargins(1, 1, 1, 1)
        self.selectionLayout.setSpacing(3)
        self.selectionLayout.setObjectName("selectionLayout")
        self.spectComboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectComboBox.sizePolicy().hasHeightForWidth())
        self.spectComboBox.setSizePolicy(sizePolicy)
        self.spectComboBox.setMaxVisibleItems(5)
        self.spectComboBox.setObjectName("spectComboBox")
        self.selectionLayout.addWidget(self.spectComboBox, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.selectionLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.selectionLayout.addWidget(self.label, 3, 0, 1, 1)
        self.alphaSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alphaSpinBox.sizePolicy().hasHeightForWidth())
        self.alphaSpinBox.setSizePolicy(sizePolicy)
        self.alphaSpinBox.setMaximum(255)
        self.alphaSpinBox.setProperty("value", 175)
        self.alphaSpinBox.setObjectName("alphaSpinBox")
        self.selectionLayout.addWidget(self.alphaSpinBox, 3, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openButton = QtWidgets.QToolButton(self.widget)
        self.openButton.setIconSize(QtCore.QSize(10, 10))
        self.openButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.openButton.setObjectName("openButton")
        self.horizontalLayout.addWidget(self.openButton)
        self.spectSumButton = QtWidgets.QToolButton(self.widget)
        self.spectSumButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.spectSumButton.setObjectName("spectSumButton")
        self.horizontalLayout.addWidget(self.spectSumButton)
        self.appendButton = QtWidgets.QToolButton(self.widget)
        self.appendButton.setCheckable(True)
        self.appendButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.appendButton.setObjectName("appendButton")
        self.horizontalLayout.addWidget(self.appendButton)
        self.selectionLayout.addWidget(self.widget, 0, 0, 1, 2)
        self.bkg_groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.bkg_groupBox.setEnabled(True)
        self.bkg_groupBox.setObjectName("bkg_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.bkg_groupBox)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bkgCheckBox = QtWidgets.QCheckBox(self.bkg_groupBox)
        self.bkgCheckBox.setObjectName("bkgCheckBox")
        self.verticalLayout.addWidget(self.bkgCheckBox)
        self.bkgTypeComboBox = QtWidgets.QComboBox(self.bkg_groupBox)
        self.bkgTypeComboBox.setEnabled(False)
        self.bkgTypeComboBox.setObjectName("bkgTypeComboBox")
        self.bkgTypeComboBox.addItem("")
        self.bkgTypeComboBox.addItem("")
        self.bkgTypeComboBox.addItem("")
        self.bkgTypeComboBox.addItem("")
        self.verticalLayout.addWidget(self.bkgTypeComboBox)
        self.slopeSpinBox = QtWidgets.QDoubleSpinBox(self.bkg_groupBox)
        self.slopeSpinBox.setEnabled(False)
        self.slopeSpinBox.setMinimum(0.0)
        self.slopeSpinBox.setProperty("value", 1.0)
        self.slopeSpinBox.setObjectName("slopeSpinBox")
        self.verticalLayout.addWidget(self.slopeSpinBox)
        self.selectionLayout.addWidget(self.bkg_groupBox, 2, 0, 1, 2)
        self.spectraTreeView = QtWidgets.QTreeView(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectraTreeView.sizePolicy().hasHeightForWidth())
        self.spectraTreeView.setSizePolicy(sizePolicy)
        self.spectraTreeView.setMinimumSize(QtCore.QSize(150, 0))
        self.spectraTreeView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.spectraTreeView.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.spectraTreeView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.spectraTreeView.setObjectName("spectraTreeView")
        self.selectionLayout.addWidget(self.spectraTreeView, 1, 0, 1, 2)
        self.spect_widget_container = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spect_widget_container.sizePolicy().hasHeightForWidth())
        self.spect_widget_container.setSizePolicy(sizePolicy)
        self.spect_widget_container.setObjectName("spect_widget_container")
        self.verticalLayout_2.addWidget(self.splitter)
        self.label_2.setBuddy(self.spectComboBox)
        self.label.setBuddy(self.alphaSpinBox)

        self.retranslateUi(WDSScanWidget)
        self.appendButton.toggled['bool'].connect(self.bkg_groupBox.setVisible)
        self.bkgCheckBox.toggled['bool'].connect(self.bkgTypeComboBox.setEnabled)
        self.bkgCheckBox.toggled['bool'].connect(self.slopeSpinBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(WDSScanWidget)

    def retranslateUi(self, WDSScanWidget):
        _translate = QtCore.QCoreApplication.translate
        WDSScanWidget.setWindowTitle(_translate("WDSScanWidget", "Form"))
        self.spectComboBox.setToolTip(_translate("WDSScanWidget", "Unique combinations of spectrometer + XTAL"))
        self.label_2.setText(_translate("WDSScanWidget", "spect/xtal:"))
        self.label.setText(_translate("WDSScanWidget", "alpha:"))
        self.alphaSpinBox.setToolTip(_translate("WDSScanWidget", "Transparency of WDS curves (alpha value)"))
        self.openButton.setText(_translate("WDSScanWidget", "Open"))
        self.spectSumButton.setText(_translate("WDSScanWidget", "∑"))
        self.appendButton.setText(_translate("WDSScanWidget", "bg"))
        self.bkgCheckBox.setText(_translate("WDSScanWidget", "Enable background\n"
" modeling for selected"))
        self.bkgTypeComboBox.setItemText(0, _translate("WDSScanWidget", "Linear"))
        self.bkgTypeComboBox.setItemText(1, _translate("WDSScanWidget", "Exponential"))
        self.bkgTypeComboBox.setItemText(2, _translate("WDSScanWidget", "Left only"))
        self.bkgTypeComboBox.setItemText(3, _translate("WDSScanWidget", "Right only"))
